install: wget http://gnu.askapache.com/gsl/gsl-latest.tar.gz;
tar -xvf gsl-latest.tar.gz; 
cd gsl-2.1/;./configure;make;make install
language: c

compiler: gcc

script: gcc -Wall cauldron/eam_mc.c cauldron/eam_functions.c cauldron/math_functions.c cauldron/utils.c -o cauldron/a.out -lgsl -lgslcblas -lm
