before_install:
  - ./install_gsl_tavis.sh

install: true
language: c

compiler: gcc

script: gcc -Wall cauldron/eam_mc.c cauldron/eam_functions.c cauldron/math_functions.c cauldron/utils.c -o cauldron/a.out -lgsl -lgslcblas -lm
